services:
  wow_server:
    build:
      context: ../..
      dockerfile: build/server/Dockerfile
    image: "wow_server:latest"
    container_name: wow_server
    ports:
      - "8080:8080"
    environment:
      - ADDR=0.0.0.0:8080
      - NAME=WORD_OF_WISDOM_SERVER
      - DIFFICULTY=3
      - DEADLINE=10s
    # healthcheck:
    #   test: ["CMD", "sh", "-c", "nc -z localhost 8080"]
    #   interval: 30s
    #   timeout: 10s
    #   retries: 3
    #   start_period: 10s

  wow_client:
    build:
      context: ../..
      dockerfile: build/client/Dockerfile
    image: "wow_client:latest"
    container_name: wow_client
    environment:
      - SERVER_ADDR=wow_server:8080
      - NAME=WORD_OF_WISDOM_CLIENT
    depends_on:
      - wow_server